import os
import io
import pandas as pd
from flask import request, jsonify, send_file
from flask_cors import CORS
from app import create_app
from app.scanner import scan_local_directory

# ReportLab libraries for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

app = create_app()
CORS(app)

DATASET_PATH = os.path.join(os.path.dirname(__file__), 'dataset.csv')

# --- Existing Endpoint ---
@app.route('/api/scan-local-dir', methods=['POST'])
def handle_scan_dir():
    data = request.json or {}
    target_path = data.get('target_path', '')

    if not target_path:
        return jsonify({"error": "Target directory path is required"}), 400

    df = scan_local_directory(target_path)
    
    if df.empty:
        return jsonify({"error": "Path not found or no accessible files in directory"}), 404

    df.to_csv(DATASET_PATH, index=False)
    
    return jsonify({
        "message": f"Successfully scanned {len(df)} local files.",
        "total_files": len(df),
        "path": target_path
    })

# ==========================================
# STEP 2: AUTOMATED DATA CLEANUP ENDPOINT
# ==========================================
@app.route('/api/cleanup-dark-files', methods=['POST'])
def handle_cleanup():
    if not os.path.exists(DATASET_PATH):
        return jsonify({"error": "No dataset found to clean."}), 404

    df = pd.read_csv(DATASET_PATH)
    
    # Identify files flagged for deletion or cold storage based on business logic/model tags
    # Filter out files recommended for deletion or move
    initial_count = len(df)
    
    # Flagged condition: high age, low access count or flagged by AI
    if 'automated_action' in df.columns:
        dark_files = df[df['automated_action'] == 'Recommend Deletion']
        df = df[df['automated_action'] != 'Recommend Deletion']
    else:
        # Fallback heuristic: creation > 180 days & 0 access in 30d
        dark_files = df[(df['days_since_creation'] > 180) & (df['access_count_30d'] == 0)]
        df = df[~((df['days_since_creation'] > 180) & (df['access_count_30d'] == 0))]

    deleted_count = len(dark_files)
    
    # Save updated clean dataset
    df.to_csv(DATASET_PATH, index=False)

    # Optional: Delete actual local files if file_id contains absolute path
    actual_deleted_physical_files = 0
    for _, row in dark_files.iterrows():
        file_path = str(row.get('file_id', ''))
        if os.path.isabs(file_path) and os.path.exists(file_path):
            try:
                os.remove(file_path)
                actual_deleted_physical_files += 1
            except Exception as e:
                print(f"Could not delete physical file {file_path}: {e}")

    return jsonify({
        "message": f"Successfully cleaned up {deleted_count} dark data files.",
        "dataset_files_removed": deleted_count,
        "physical_files_deleted": actual_deleted_physical_files,
        "remaining_files": len(df)
    })

# ==========================================
# STEP 3: PDF AUDIT REPORT GENERATOR ENDPOINT
# ==========================================
@app.route('/api/download-pdf-report', methods=['GET'])
def download_pdf_report():
    if not os.path.exists(DATASET_PATH):
        return jsonify({"error": "No data available to generate report."}), 404

    df = pd.read_csv(DATASET_PATH)
    total_files = len(df)
    
    # Calculate basic carbon & storage metrics
    total_mb = df['file_size_mb'].sum() if 'file_size_mb' in df.columns else 0
    total_gb = total_mb / 1024.0
    
    # Estimated carbon (0.2 g CO2 per GB per month)
    carbon_g = total_gb * 0.2 * 1000  # in mg/g
    
    dark_count = 0
    if 'automated_action' in df.columns:
        dark_count = len(df[df['automated_action'] != 'Retain Active Tier'])
    else:
        dark_count = len(df[df['days_since_creation'] > 180])

    dark_percentage = (dark_count / total_files * 100) if total_files > 0 else 0

    # Generate PDF in memory buffer
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#475569'),
        spaceAfter=20
    )

    # Document Header
    story.append(Paragraph("<b>Dark Data & Sustainability Audit Report</b>", title_style))
    story.append(Paragraph("Generated by Energy-Aware Dark Data Auditor | AI-Powered Cloud Sustainability", subtitle_style))
    story.append(Spacer(1, 10))

    # Executive Summary Table
    summary_data = [
        ["Metric", "Value"],
        ["Total Files Audited", f"{total_files:,}"],
        ["Total Storage Size", f"{total_gb:.2f} GB ({total_mb:.1f} MB)"],
        ["Identified Dark Data Files", f"{dark_count} ({dark_percentage:.1f}%)"],
        ["Current Carbon Footprint", f"{carbon_g:.2f} g CO₂ / month"],
        ["Est. Monthly Cost Savings Potential", f"${(dark_count * 0.02):.2f} USD"]
    ]

    t = Table(summary_data, colWidths=[250, 250])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
    ]))
    story.append(t)
    story.append(Spacer(1, 25))

    # Top Dark Files List Preview (Up to 10 rows)
    story.append(Paragraph("<b>Top Flagged Dark Data Files</b>", styles['Heading2']))
    story.append(Spacer(1, 8))

    file_table_data = [["File ID / Path", "Type", "Size (MB)", "Days Old", "Action"]]
    
    sample_files = df.head(10)
    for _, row in sample_files.iterrows():
        file_id = str(row.get('file_id', 'Unknown'))
        if len(file_id) > 35:
            file_id = '...' + file_id[-32:]
        file_type = str(row.get('file_type', 'N/A'))
        size = f"{row.get('file_size_mb', 0):.2f}"
        days = str(row.get('days_since_creation', 0))
        action = str(row.get('automated_action', 'Flagged'))

        file_table_data.append([file_id, file_type, size, days, action])

    ft = Table(file_table_data, colWidths=[200, 60, 60, 60, 120])
    ft.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#334155')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(ft)

    doc.build(story)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="Dark_Data_Audit_Report.pdf",
        mimetype="application/pdf"
    )

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=False, host="0.0.0.0", port=port, threaded=True)