from flask import Blueprint, jsonify, request
import pandas as pd
import numpy as np
import pickle
import os
import csv
import random
import hashlib

main_bp = Blueprint('main', __name__)

# System file paths
CSV_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'cloud_metadata.csv')
MODEL_PATH = os.path.join(os.path.dirname(__file__), '..', 'models', 'dark_data_classifier.pkl')

# The exact columns the classifier and dashboard expect in any dataset,
# whether it's generated by us or uploaded by the user.
REQUIRED_COLUMNS = [
    'file_id', 'file_type', 'file_size_mb',
    'days_since_creation', 'days_since_last_accessed', 'access_count_30d'
]

# PART 3: Carbon Coefficients Constants (Data Carbon Ladder Estimation Metrics)
# Industry reference values for Data Center Power Usage Effectiveness (PUE) and storage wattages
PUE = 1.5  
WATT_PER_GB_HOT = 0.0000114  # Active storage power draw per hour
WATT_PER_GB_COLD = 0.0000015 # Cold archive storage power draw per hour (85%+ lower energy footprint)
GRID_CARBON_INTENSITY = 0.42 # Average global kg CO2 produced per kWh of grid electricity consumed

def calculate_sustainability_metrics(size_mb, days_old, is_dark):
    """Calculates operational energy consumption and environmental carbon footprint impacts"""
    size_gb = size_mb / 1024.0
    hours_stored = days_old * 24.0
    
    # Calculate energy overhead under baseline hot storage conditions
    energy_kwh_hot = (size_gb * WATT_PER_GB_HOT * hours_stored * PUE) / 1000.0
    carbon_kg_hot = energy_kwh_hot * GRID_CARBON_INTENSITY
    
    # Calculate potential carbon savings if migrated down to cold archival tier
    energy_kwh_cold = (size_gb * WATT_PER_GB_COLD * hours_stored * PUE) / 1000.0
    carbon_kg_cold = energy_kwh_cold * GRID_CARBON_INTENSITY
    
    potential_savings_kg = carbon_kg_hot - carbon_kg_cold if is_dark else 0.0
    
    return {
        "current_carbon_kg": round(carbon_kg_hot, 6),
        "cold_carbon_kg": round(carbon_kg_cold, 6),
        "potential_savings_kg": round(potential_savings_kg, 6)
    }

@main_bp.route('/api/generate-dataset', methods=['POST'])
def generate_dataset():
    """
    Creates a brand new synthetic cloud metadata dataset (same logic as
    generate_mock_data.py) and saves it as the active dataset, so the
    dashboard immediately reflects it on the next fetch.
    """
    body = request.get_json(silent=True) or {}
    num_files = int(body.get('num_files', 5000))
    num_files = max(50, min(num_files, 20000))  # keep it within a sane range

    file_extensions = ['.pdf', '.zip', '.docx', '.xlsx', '.log', '.tmp', '.bak', '.png']
    dark_seed_cutoff = int(num_files * 0.8)  # last ~20% are forced heavy "dark" files

    os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)
    with open(CSV_PATH, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(REQUIRED_COLUMNS)

        for i in range(1, num_files + 1):
            is_dark_seed = i > dark_seed_cutoff

            file_id = f"FILE_{i:04d}" if not is_dark_seed else f"DARK_SYS_BAK_{i}"
            f_type = random.choice(file_extensions) if not is_dark_seed else random.choice(['.zip', '.bak', '.log'])
            size = round(random.uniform(500.0, 4500.0), 2) if is_dark_seed else round(random.uniform(50.0, 800.0), 2)
            days_old = random.randint(150, 600) if is_dark_seed else random.randint(10, 180)

            if is_dark_seed:
                days_unaccessed = random.randint(120, days_old)
                access_30d = 0
            else:
                days_unaccessed = random.randint(0, min(days_old, 30))
                access_30d = random.randint(5, 50)

            writer.writerow([file_id, f_type, size, days_old, days_unaccessed, access_30d])

    return jsonify({
        "message": f"Generated a new synthetic dataset with {num_files} files.",
        "num_files": num_files
    }), 200


@main_bp.route('/api/connect-aws-bucket', methods=['POST'])
def connect_aws_bucket():
    """
    Connects to a real AWS S3 bucket, lists every object in it, and builds
    a dataset from their real metadata (size, key/name, last-modified date).

    Credentials are read from environment variables (loaded from a local
    .env file via python-dotenv) - never hardcoded, never sent by the
    frontend, never stored anywhere in this codebase.

    Like the local folder scan, S3 doesn't expose a true "creation date" or
    access-count history either - only size and last-modified time are
    real; age/last-accessed are approximated from last-modified, and
    access_count_30d defaults to 0. This is a disclosed limitation, not a bug.
    """
    import boto3
    from botocore.exceptions import ClientError, NoCredentialsError
    from datetime import datetime, timezone

    access_key = os.environ.get('AWS_ACCESS_KEY_ID')
    secret_key = os.environ.get('AWS_SECRET_ACCESS_KEY')
    region = os.environ.get('AWS_REGION')
    bucket_name = os.environ.get('AWS_BUCKET_NAME')

    if not all([access_key, secret_key, region, bucket_name]):
        return jsonify({
            "error": "AWS credentials are not configured. Create a .env file in the "
                     "backend folder (see .env.example) with your AWS_ACCESS_KEY_ID, "
                     "AWS_SECRET_ACCESS_KEY, AWS_REGION, and AWS_BUCKET_NAME."
        }), 400

    try:
        s3 = boto3.client(
            's3',
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name=region,
        )
        response = s3.list_objects_v2(Bucket=bucket_name)
    except NoCredentialsError:
        return jsonify({"error": "AWS credentials were rejected. Check your Access Key and Secret Key."}), 401
    except ClientError as e:
        error_code = e.response.get('Error', {}).get('Code', 'Unknown')
        return jsonify({"error": f"AWS error ({error_code}): could not access bucket '{bucket_name}'. "
                                  f"Check the bucket name and region."}), 400
    except Exception as e:
        return jsonify({"error": f"Could not connect to AWS: {str(e)}"}), 500

    objects = response.get('Contents', [])
    if not objects:
        return jsonify({"error": f"Bucket '{bucket_name}' is empty. Upload some files to it first."}), 400

    now = datetime.now(timezone.utc)
    rows = [REQUIRED_COLUMNS + ['source', 's3_key']]

    for obj in objects:
        key = obj['Key']
        size_mb = round(obj['Size'] / (1024 * 1024), 4)
        last_modified = obj['LastModified']
        days_since_modified = max(0, (now - last_modified).days)
        ext = os.path.splitext(key)[1].lower() or '.unknown'

        rows.append([
            f"S3_{key.replace('/', '_').replace(',', '_')}",
            ext,
            size_mb,
            days_since_modified,   # approximated age - see docstring
            days_since_modified,   # approximated last-accessed - see docstring
            0,                     # access count not available from S3 metadata
            's3',
            key,                   # the REAL, exact S3 key - used directly for migration, never reconstructed
        ])

    os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)
    with open(CSV_PATH, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(rows)

    return jsonify({
        "message": f"Connected to bucket '{bucket_name}' and loaded {len(objects)} real files.",
        "num_files": len(objects),
        "bucket": bucket_name,
    }), 200



def upload_dataset():
    """
    Accepts a user-uploaded CSV file, validates it has the columns the
    classifier needs, and saves it as the active dataset.
    """
    if 'file' not in request.files:
        return jsonify({"error": "No file was uploaded."}), 400

    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
        return jsonify({"error": "No file was selected."}), 400
    if not uploaded_file.filename.lower().endswith('.csv'):
        return jsonify({"error": "Only .csv files are supported."}), 400

    try:
        df = pd.read_csv(uploaded_file)
    except Exception as e:
        return jsonify({"error": f"Could not read that file as a CSV: {str(e)}"}), 400

    missing_columns = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing_columns:
        return jsonify({
            "error": "Your CSV is missing required columns: " + ", ".join(missing_columns),
            "required_columns": REQUIRED_COLUMNS
        }), 400

    os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)
    df.to_csv(CSV_PATH, index=False)

    return jsonify({
        "message": f"Uploaded dataset with {len(df)} files.",
        "num_files": len(df)
    }), 200


@main_bp.route('/api/retrain-model', methods=['POST'])
def retrain_model():
    """
    Retrains the AI classifier on whatever dataset is currently active
    (data/cloud_metadata.csv), using the same rule-based labeling and
    RandomForest approach as train_classifier.py, then overwrites the
    saved model so future predictions use the freshly trained version.
    """
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import accuracy_score

    if not os.path.exists(CSV_PATH):
        return jsonify({"error": "No dataset found. Generate or upload one first."}), 400

    df = pd.read_csv(CSV_PATH)

    missing_columns = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing_columns:
        return jsonify({"error": "Dataset is missing required columns: " + ", ".join(missing_columns)}), 400

    # Rule-based ground truth: same definition of "dark data" used originally
    df['is_dark'] = np.where(
        (df['days_since_last_accessed'] > 180) & (df['access_count_30d'] == 0), 1, 0
    )

    features = ['file_size_mb', 'days_since_creation', 'days_since_last_accessed', 'access_count_30d']
    X = df[features]
    y = df['is_dark']

    if y.nunique() < 2:
        return jsonify({
            "error": "This dataset only contains one class (all active or all dark). "
                     "Retraining needs a mix of both to learn from."
        }), 400

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    with open(MODEL_PATH, 'wb') as f:
        pickle.dump(model, f)

    return jsonify({
        "message": "Model retrained successfully on the current dataset.",
        "accuracy_percent": round(accuracy * 100, 2),
        "training_rows": len(X_train),
        "test_rows": len(X_test)
    }), 200


def pseudonymize_id(file_id: str) -> str:
    """
    Converts a file identifier into an anonymous, non-reversible code.
    Used in Privacy Mode so that no original file naming patterns
    (which could hint at content or ownership) are ever sent to the browser.
    """
    digest = hashlib.sha256(str(file_id).encode()).hexdigest()[:10].upper()
    return f"ANON-{digest}"


@main_bp.route('/api/run-benchmark', methods=['POST'])
def run_benchmark():
    """
    Runs the multi-model comparison (Decision Tree, Random Forest,
    Logistic Regression, Linear SVM, Gradient Boosting) and returns
    accuracy, F1 score, and estimated carbon footprint for each -
    used by the "AI Research Lab" panel to justify the model choice.
    """
    from app.research_engine import run_multi_model_benchmark

    body = request.get_json(silent=True) or {}
    num_samples = int(body.get('num_samples', 800))
    num_samples = max(200, min(num_samples, 5000))

    try:
        results = run_multi_model_benchmark(num_samples=num_samples)
    except Exception as e:
        return jsonify({"error": f"Benchmark failed: {str(e)}"}), 500

    return jsonify({"results": results, "num_samples": num_samples}), 200


@main_bp.route('/api/migrate-dark-files', methods=['POST'])
def migrate_dark_files():
    """
    Actually performs the automated lifecycle action your proposal promises:
    any file the AI flags as "Migrate to Cold Storage" gets permanently
    marked as migrated. From then on, its carbon footprint is recalculated
    using cheap cold-storage energy costs instead of expensive hot-storage
    costs - a real, persisted change, not just a label in a table.
    """
    if not os.path.exists(CSV_PATH) or not os.path.exists(MODEL_PATH):
        return jsonify({"error": "No dataset or model available yet."}), 404

    df = pd.read_csv(CSV_PATH)
    with open(MODEL_PATH, 'rb') as f:
        model = pickle.load(f)

    if 'migrated' not in df.columns:
        df['migrated'] = 0

    features = ['file_size_mb', 'days_since_creation', 'days_since_last_accessed', 'access_count_30d']
    df['ai_prediction'] = model.predict(df[features])

    # Same eligibility rule the dashboard uses to label "Migrate to Cold Storage"
    eligible = (df['ai_prediction'] == 1) & (df['file_type'] != '.tmp') & (df['migrated'] == 0)

    carbon_prevented = 0.0
    for idx in df[eligible].index:
        stats = calculate_sustainability_metrics(
            df.loc[idx, 'file_size_mb'], df.loc[idx, 'days_since_creation'], True
        )
        carbon_prevented += stats['potential_savings_kg']

    files_migrated = int(eligible.sum())
    df.loc[eligible, 'migrated'] = 1

    # For files that actually came from a real AWS S3 bucket (source == 's3'),
    # perform a genuine cloud action: change their storage class to GLACIER,
    # AWS's real low-energy archival tier. This is not simulated - it's a
    # real API call that changes the real object in your real bucket.
    s3_migrated_count = 0
    s3_errors = []
    if 'source' in df.columns:
        s3_eligible = eligible & (df['source'] == 's3')
        if s3_eligible.any():
            import boto3
            from botocore.exceptions import ClientError

            access_key = os.environ.get('AWS_ACCESS_KEY_ID')
            secret_key = os.environ.get('AWS_SECRET_ACCESS_KEY')
            region = os.environ.get('AWS_REGION')
            bucket_name = os.environ.get('AWS_BUCKET_NAME')

            if all([access_key, secret_key, region, bucket_name]):
                s3 = boto3.client(
                    's3', aws_access_key_id=access_key,
                    aws_secret_access_key=secret_key, region_name=region,
                )
                for idx in df[s3_eligible].index:
                    # Use the exact key stored during ingestion - never reconstructed from
                    # file_id, since filenames can themselves contain underscores or commas
                    # that would make reversing that encoding ambiguous and unsafe.
                    key = df.loc[idx, 's3_key']
                    try:
                        s3.copy_object(
                            Bucket=bucket_name,
                            CopySource={'Bucket': bucket_name, 'Key': key},
                            Key=key,
                            StorageClass='GLACIER',
                        )
                        s3_migrated_count += 1
                    except ClientError as e:
                        s3_errors.append(f"{key}: {e.response.get('Error', {}).get('Code', 'error')}")

    # Drop the temporary prediction column before saving - it gets recalculated fresh each time anyway
    df = df.drop(columns=['ai_prediction'])
    df.to_csv(CSV_PATH, index=False)

    message = f"Migrated {files_migrated} files to cold storage."
    if s3_migrated_count:
        message += f" {s3_migrated_count} of these were real AWS S3 objects, moved to Glacier storage class."
    if s3_errors:
        message += f" ({len(s3_errors)} S3 files could not be migrated - check bucket permissions.)"

    return jsonify({
        "message": message,
        "files_migrated": files_migrated,
        "s3_files_migrated": s3_migrated_count,
        "carbon_prevented_kg": round(carbon_prevented, 4)
    }), 200


@main_bp.route('/api/dashboard-metrics', methods=['GET'])
def get_dashboard_data():
    if not os.path.exists(CSV_PATH) or not os.path.exists(MODEL_PATH):
        return jsonify({"error": "Core model or data pipeline components are missing."}), 404

    # Privacy Mode: when enabled, real file identifiers never leave the server.
    anonymize = request.args.get('anonymize', 'false').lower() == 'true'
    
    # 1. Load data and machine learning model
    df = pd.read_csv(CSV_PATH)
    with open(MODEL_PATH, 'rb') as f:
        model = pickle.load(f)

    if 'migrated' not in df.columns:
        df['migrated'] = 0

    # 2. Run active live inference across all tracked storage arrays
    features = ['file_size_mb', 'days_since_creation', 'days_since_last_accessed', 'access_count_30d']
    df['ai_prediction'] = model.predict(df[features])

    # How confident the model is in each of its own predictions (0-100%)
    probabilities = model.predict_proba(df[features])
    df['confidence_percent'] = np.round(probabilities.max(axis=1) * 100, 1)

    # 3. Inject Carbon Assessment calculations
    carbon_stats = [calculate_sustainability_metrics(r['file_size_mb'], r['days_since_creation'], r['ai_prediction']) for _, r in df.iterrows()]

    # Files already migrated run at cold-storage energy cost; everything else at hot-storage cost
    df['carbon_kg'] = [
        c['cold_carbon_kg'] if migrated == 1 else c['current_carbon_kg']
        for c, migrated in zip(carbon_stats, df['migrated'])
    ]

    # 4. Execute Closed-loop Lifecycle Automation Policy Decisions
    df['automated_action'] = np.where(
        df['migrated'] == 1,
        'Already Migrated (Cold Storage)',
        np.where(
            df['ai_prediction'] == 1,
            np.where(df['file_type'] == '.tmp', 'Recommend Deletion', 'Migrate to Cold Storage'),
            'Retain Active Tier'
        )
    )

    # 5. Compile Global Aggregates
    total_dark_files = int(df['ai_prediction'].sum())
    total_active_files = len(df) - total_dark_files

    # Financial ROI calculation
    dark_data_size_gb = df[df['ai_prediction'] == 1]['file_size_mb'].sum() / 1024.0
    monthly_financial_roi = dark_data_size_gb * (0.023 - 0.004)

    # Real prevented emissions: the actual carbon saved by files already migrated,
    # calculated from the difference between their old hot-storage cost and their
    # current cold-storage cost (no longer a hardcoded placeholder value)
    migrated_rows = df['migrated'] == 1
    prevented_emissions_kg = 0.0
    if migrated_rows.any():
        for idx in df[migrated_rows].index:
            stats = calculate_sustainability_metrics(
                df.loc[idx, 'file_size_mb'], df.loc[idx, 'days_since_creation'], True
            )
            prevented_emissions_kg += stats['potential_savings_kg']

    # Pass the entire dataset array to allow full vertical scrolling in the UI stream
    if anonymize:
        df['file_id'] = df['file_id'].apply(pseudonymize_id)
    file_list = df.drop(columns=['ai_prediction']).to_dict(orient='records')

    return jsonify({
        "privacy_mode": anonymize,
        "aggregates": {
            "total_files": len(df),
            "dark_files_count": total_dark_files,
            "active_files_count": total_active_files,
            "current_footprint_kg": round(float(df['carbon_kg'].sum()), 2),
            "prevented_emissions_kg": round(prevented_emissions_kg, 4),
            "estimated_monthly_roi_usd": round(monthly_financial_roi, 2),
            "files_migrated_count": int(migrated_rows.sum())
        },
        "files": file_list
    }), 200